In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good",]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
vocab_size = 10000

In [5]:
### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,vocab_size)for words in sent] 
print(onehot_repr)

[[3530, 744, 9123, 9986], [3530, 744, 9123, 4057], [3530, 259, 9123, 8468], [3055, 2815, 5990, 2537, 9374], [3055, 2815, 5990, 2537, 7186], [9020, 3530, 5149, 9123, 3135], [2130, 5309, 6736, 2537]]


In [9]:
### Word Embedding Reresentation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3530  744 9123 9986]
 [   0    0    0    0 3530  744 9123 4057]
 [   0    0    0    0 3530  259 9123 8468]
 [   0    0    0 3055 2815 5990 2537 9374]
 [   0    0    0 3055 2815 5990 2537 7186]
 [   0    0    0 9020 3530 5149 9123 3135]
 [   0    0    0    0 2130 5309 6736 2537]]


In [13]:
dim=10

In [15]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876
   -0.00455588  0.04707328 -0.02760085 -0.03376036  0.03260381]
  [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876
   -0.00455588  0.04707328 -0.02760085 -0.03376036  0.03260381]
  [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876
   -0.00455588  0.04707328 -0.02760085 -0.03376036  0.03260381]
  [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876
   -0.00455588  0.04707328 -0.02760085 -0.03376036  0.03260381]
  [-0.04215865  0.02134157 -0.00057445  0.03284805 -0.03187533
    0.03138674  0.04314793  0.03758482 -0.02817451  0.03847631]
  [-0.0103872   0.00300167  0.00767245  0.04122842  0.00917745
   -0.02904054  0.00863619 -0.02786197  0.00922974  0.02697711]
  [-0.04199569 -0.04577623 -0.04294835  0.02147343  0.03504891
   -0.01912323 -0.02677138 -0.00854417  0.03201533 -0.02118863]
  [-0.00507087  0.04974825 -0.00659155  0.02686672 -0.00565766
   -0.00464522  0.02116339 -0.00240433 -0.025974

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3530,  744, 9123, 9986], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

[[ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876 -0.00455588
   0.04707328 -0.02760085 -0.03376036  0.03260381]
 [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876 -0.00455588
   0.04707328 -0.02760085 -0.03376036  0.03260381]
 [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876 -0.00455588
   0.04707328 -0.02760085 -0.03376036  0.03260381]
 [ 0.00722843  0.01066535 -0.0331717   0.02446438  0.01039876 -0.00455588
   0.04707328 -0.02760085 -0.03376036  0.03260381]
 [-0.04215865  0.02134157 -0.00057445  0.03284805 -0.03187533  0.03138674
   0.04314793  0.03758482 -0.02817451  0.03847631]
 [-0.0103872   0.00300167  0.00767245  0.04122842  0.00917745 -0.02904054
   0.00863619 -0.02786197  0.00922974  0.02697711]
 [-0.04199569 -0.04577623 -0.04294835  0.02147343  0.03504891 -0.01912323
  -0.02677138 -0.00854417  0.03201533 -0.02118863]
 [-0.00507087  0.04974825 -0.00659155  0.02686672 -0.00565766 -0.00464522
   0.02116339 -0.00240433 -0.0259742   0.02021537]]